openapi: 3.0.3
info:
  description: "API dùng để quản lý sách trong thư viện, có hỗ trợ phân trang."
  title: Book Management API
  version: 1.1.0
servers:
- description: Local server
  url: http://localhost:5000/api
paths:
  /books:
    get:
      operationId: books_get
      parameters:
      - description: Trang hiện tại (bắt đầu từ 1)
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Số lượng sách trên mỗi trang
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 5
          maximum: 100
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_books_get_200_response"
          description: Danh sách sách (có thông tin phân trang)
      summary: Lấy danh sách sách (có hỗ trợ phân trang)
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: books_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: Sách đã được thêm thành công
      summary: Thêm một sách mới
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /books/{id}:
    delete:
      operationId: books_id_delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: Xóa thành công
        "404":
          description: Không tìm thấy sách
      summary: Xóa sách theo ID
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: books_id_get
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: Thông tin sách
        "404":
          description: Không tìm thấy sách
      summary: Lấy thông tin chi tiết một sách
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      operationId: books_id_put
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: Cập nhật thành công
      summary: Cập nhật thông tin sách
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Book:
      example:
        id: 1
        title: The Great Gatsby
        author: F. Scott Fitzgerald
        year: 1925
        genre: Fiction
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        year:
          type: integer
        genre:
          type: string
      title: Book
      type: object
    BookInput:
      example:
        year: 0
        author: author
        genre: genre
        title: title
      properties:
        title:
          title: title
          type: string
        author:
          title: author
          type: string
        year:
          title: year
          type: integer
        genre:
          title: genre
          type: string
      required:
      - author
      - title
      title: BookInput
      type: object
    _books_get_200_response:
      example:
        has_next: true
        page: 1
        total_pages: 10
        has_prev: false
        total_items: 47
        items:
        - id: 1
          title: The Great Gatsby
          author: F. Scott Fitzgerald
          year: 1925
          genre: Fiction
        - id: 1
          title: The Great Gatsby
          author: F. Scott Fitzgerald
          year: 1925
          genre: Fiction
      properties:
        page:
          example: 1
          title: page
          type: integer
        total_pages:
          example: 10
          title: total_pages
          type: integer
        total_items:
          example: 47
          title: total_items
          type: integer
        has_next:
          example: true
          title: has_next
          type: boolean
        has_prev:
          example: false
          title: has_prev
          type: boolean
        items:
          items:
            $ref: "#/components/schemas/Book"
          title: items
          type: array
      title: _books_get_200_response
      type: object
